version: '3'
services:
  emqx:
    image: emqx/emqx-enterprise:5.9.0
    container_name: qos-msg-idea
    environment:
      EMQX_NODE__NAME: qos-msg@127.0.0.1
      EMQX_CLUSTER__NAME: qos-msg-cluster
    volumes:
      - ./qos-data:/opt/emqx/data
      - ./qos-logs:/opt/emqx/log
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8083:8083"
    restart: always

  mysql:
    image: mysql:8.0.18
    container_name: mysql-idea
    environment:
      MYSQL_ROOT_PASSWORD: public
    ports:
      - "3306:3306"
    restart: always
    volumes:
      # 将本地的 sql/init.sql 文件挂载到容器内的 /docker-entrypoint-initdb.d/init.sql
      - ./sql:/docker-entrypoint-initdb.d:ro

  my_app:
    build: .
    container_name: my_app-idea
    depends_on:
      - mysql
      - emqx
    volumes:
      - ./api/config.js:/app/api/config.js
      - ./api/index.js:/app/api/index.js
    ports:
      - "3000:3000"
    restart: always
